INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (100, 288000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (101, 204000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (102, 204000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (103, 108000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (104, 72000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (105, 57600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (106, 57600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (107, 50400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (108, 144000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (109, 108000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (110, 98400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (111, 92400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (112, 93600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (113, 82800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (114, 132000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (115, 37200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (116, 34800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (117, 33600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (118, 31200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (119, 30000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (120, 96000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (121, 98400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (122, 94800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (123, 78000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (124, 69600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (125, 38400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (126, 32400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (127, 28800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (128, 26400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (129, 39600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (130, 33600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (131, 30000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (132, 25200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (133, 39600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (134, 34800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (135, 28800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (136, 26400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (137, 43200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (138, 38400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (139, 32400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (140, 30000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (141, 42000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (142, 37200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (143, 31200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (144, 30000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (145, 235200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (146, 210600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (147, 187200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (148, 171600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (149, 151200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (150, 156000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (151, 142500.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (152, 135000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (153, 115200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (154, 108000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (155, 96600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (156, 162000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (157, 153900.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (158, 145800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (159, 124800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (160, 117000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (161, 105000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (162, 157500.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (163, 131100.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (164, 95040.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (165, 89760.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (166, 84480.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (167, 81840.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (168, 172500.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (169, 144000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (170, 138240.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (171, 102120.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (172, 100740.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (173, 80520.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (174, 171600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (175, 132000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (176, 123840.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (177, 120960.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (178, 96600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (179, 81840.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (180, 38400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (181, 37200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (182, 30000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (183, 33600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (184, 50400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (185, 49200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (186, 40800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (187, 36000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (188, 45600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (189, 43200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (190, 34800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (191, 30000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (192, 48000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (193, 46800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (194, 38400.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (195, 33600.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (196, 37200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (197, 36000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (198, 31200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (199, 31200.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (200, 52800.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (201, 156000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (202, 72000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (203, 78000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (204, 120000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (205, 144000.00);
INSERT INTO `SELECT课后练习` (`employee_id`, `annual salary`) VALUES (206, 99600.00);
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('AC_ACCOUNT');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('AC_MGR');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('AD_ASST');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('AD_PRES');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('AD_VP');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('FI_ACCOUNT');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('FI_MGR');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('HR_REP');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('IT_PROG');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('MK_MAN');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('MK_REP');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('PR_REP');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('PU_CLERK');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('PU_MAN');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('SA_MAN');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('SA_REP');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('SH_CLERK');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('ST_CLERK');
INSERT INTO `SELECT课后练习` (`job_id`) VALUES ('ST_MAN');
INSERT INTO `SELECT课后练习` (`first_name`, `last_name`, `salary`) VALUES ('Steven', 'King', 24000.00);
INSERT INTO `SELECT课后练习` (`first_name`, `last_name`, `salary`) VALUES ('Neena', 'Kochhar', 17000.00);
INSERT INTO `SELECT课后练习` (`first_name`, `last_name`, `salary`) VALUES ('Lex', 'De Haan', 17000.00);
INSERT INTO `SELECT课后练习` (`first_name`, `last_name`, `salary`) VALUES ('John', 'Russell', 14000.00);
INSERT INTO `SELECT课后练习` (`first_name`, `last_name`, `salary`) VALUES ('Karen', 'Partners', 13500.00);
INSERT INTO `SELECT课后练习` (`first_name`, `last_name`, `salary`) VALUES ('Michael', 'Hartstein', 13000.00);
INSERT INTO `SELECT课后练习` (`first_name`, `last_name`, `department_id`) VALUES ('Jonathon', 'Taylor', 80);
INSERT INTO `SELECT课后练习` (`Field`, `Type`, `Null`, `Key`, `Default`, `Extra`) VALUES ('department_id', 'int', 'NO', 'PRI', '0', '');
INSERT INTO `SELECT课后练习` (`Field`, `Type`, `Null`, `Key`, `Default`, `Extra`) VALUES ('department_name', 'varchar(30)', 'NO', '', NULL, '');
INSERT INTO `SELECT课后练习` (`Field`, `Type`, `Null`, `Key`, `Default`, `Extra`) VALUES ('manager_id', 'int', 'YES', 'MUL', NULL, '');
INSERT INTO `SELECT课后练习` (`Field`, `Type`, `Null`, `Key`, `Default`, `Extra`) VALUES ('location_id', 'int', 'YES', 'MUL', NULL, '');
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (10, 'Administration', 200, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (20, 'Marketing', 201, 1800);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (30, 'Purchasing', 114, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (40, 'Human Resources', 203, 2400);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (50, 'Shipping', 121, 1500);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (60, 'IT', 103, 1400);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (70, 'Public Relations', 204, 2700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (80, 'Sales', 145, 2500);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (90, 'Executive', 100, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (100, 'Finance', 108, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (110, 'Accounting', 205, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (120, 'Treasury', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (130, 'Corporate Tax', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (140, 'Control And Credit', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (150, 'Shareholder Services', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (160, 'Benefits', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (170, 'Manufacturing', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (180, 'Construction', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (190, 'Contracting', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (200, 'Operations', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (210, 'IT Support', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (220, 'NOC', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (230, 'IT Helpdesk', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (240, 'Government Sales', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (250, 'Retail Sales', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (260, 'Recruiting', NULL, 1700);
INSERT INTO `SELECT课后练习` (`department_id`, `department_name`, `manager_id`, `location_id`) VALUES (270, 'Payroll', NULL, 1700);
