INSERT INTO `单行函数练习` (`NOW()`) VALUES ('2023-08-27 16:22:21');
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (100, 'King', 24000.00, 28800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (101, 'Kochhar', 17000.00, 20400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (102, 'De Haan', 17000.00, 20400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (103, 'Hunold', 9000.00, 10800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (104, 'Ernst', 6000.00, 7200.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (105, 'Austin', 4800.00, 5760.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (106, 'Pataballa', 4800.00, 5760.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (107, 'Lorentz', 4200.00, 5040.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (108, 'Greenberg', 12000.00, 14400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (109, 'Faviet', 9000.00, 10800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (110, 'Chen', 8200.00, 9840.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (111, 'Sciarra', 7700.00, 9240.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (112, 'Urman', 7800.00, 9360.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (113, 'Popp', 6900.00, 8280.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (114, 'Raphaely', 11000.00, 13200.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (115, 'Khoo', 3100.00, 3720.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (116, 'Baida', 2900.00, 3480.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (117, 'Tobias', 2800.00, 3360.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (118, 'Himuro', 2600.00, 3120.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (119, 'Colmenares', 2500.00, 3000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (120, 'Weiss', 8000.00, 9600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (121, 'Fripp', 8200.00, 9840.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (122, 'Kaufling', 7900.00, 9480.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (123, 'Vollman', 6500.00, 7800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (124, 'Mourgos', 5800.00, 6960.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (125, 'Nayer', 3200.00, 3840.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (126, 'Mikkilineni', 2700.00, 3240.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (127, 'Landry', 2400.00, 2880.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (128, 'Markle', 2200.00, 2640.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (129, 'Bissot', 3300.00, 3960.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (130, 'Atkinson', 2800.00, 3360.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (131, 'Marlow', 2500.00, 3000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (132, 'Olson', 2100.00, 2520.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (133, 'Mallin', 3300.00, 3960.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (134, 'Rogers', 2900.00, 3480.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (135, 'Gee', 2400.00, 2880.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (136, 'Philtanker', 2200.00, 2640.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (137, 'Ladwig', 3600.00, 4320.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (138, 'Stiles', 3200.00, 3840.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (139, 'Seo', 2700.00, 3240.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (140, 'Patel', 2500.00, 3000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (141, 'Rajs', 3500.00, 4200.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (142, 'Davies', 3100.00, 3720.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (143, 'Matos', 2600.00, 3120.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (144, 'Vargas', 2500.00, 3000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (145, 'Russell', 14000.00, 16800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (146, 'Partners', 13500.00, 16200.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (147, 'Errazuriz', 12000.00, 14400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (148, 'Cambrault', 11000.00, 13200.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (149, 'Zlotkey', 10500.00, 12600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (150, 'Tucker', 10000.00, 12000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (151, 'Bernstein', 9500.00, 11400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (152, 'Hall', 9000.00, 10800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (153, 'Olsen', 8000.00, 9600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (154, 'Cambrault', 7500.00, 9000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (155, 'Tuvault', 7000.00, 8400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (156, 'King', 10000.00, 12000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (157, 'Sully', 9500.00, 11400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (158, 'McEwen', 9000.00, 10800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (159, 'Smith', 8000.00, 9600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (160, 'Doran', 7500.00, 9000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (161, 'Sewall', 7000.00, 8400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (162, 'Vishney', 10500.00, 12600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (163, 'Greene', 9500.00, 11400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (164, 'Marvins', 7200.00, 8640.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (165, 'Lee', 6800.00, 8160.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (166, 'Ande', 6400.00, 7680.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (167, 'Banda', 6200.00, 7440.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (168, 'Ozer', 11500.00, 13800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (169, 'Bloom', 10000.00, 12000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (170, 'Fox', 9600.00, 11520.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (171, 'Smith', 7400.00, 8880.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (172, 'Bates', 7300.00, 8760.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (173, 'Kumar', 6100.00, 7320.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (174, 'Abel', 11000.00, 13200.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (175, 'Hutton', 8800.00, 10560.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (176, 'Taylor', 8600.00, 10320.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (177, 'Livingston', 8400.00, 10080.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (178, 'Grant', 7000.00, 8400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (179, 'Johnson', 6200.00, 7440.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (180, 'Taylor', 3200.00, 3840.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (181, 'Fleaur', 3100.00, 3720.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (182, 'Sullivan', 2500.00, 3000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (183, 'Geoni', 2800.00, 3360.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (184, 'Sarchand', 4200.00, 5040.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (185, 'Bull', 4100.00, 4920.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (186, 'Dellinger', 3400.00, 4080.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (187, 'Cabrio', 3000.00, 3600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (188, 'Chung', 3800.00, 4560.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (189, 'Dilly', 3600.00, 4320.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (190, 'Gates', 2900.00, 3480.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (191, 'Perkins', 2500.00, 3000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (192, 'Bell', 4000.00, 4800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (193, 'Everett', 3900.00, 4680.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (194, 'McCain', 3200.00, 3840.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (195, 'Jones', 2800.00, 3360.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (196, 'Walsh', 3100.00, 3720.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (197, 'Feeney', 3000.00, 3600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (198, 'OConnell', 2600.00, 3120.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (199, 'Grant', 2600.00, 3120.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (200, 'Whalen', 4400.00, 5280.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (201, 'Hartstein', 13000.00, 15600.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (202, 'Fay', 6000.00, 7200.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (203, 'Mavris', 6500.00, 7800.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (204, 'Baer', 10000.00, 12000.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (205, 'Higgins', 12000.00, 14400.00);
INSERT INTO `单行函数练习` (`employee_id`, `last_name`, `salary`, `new salary`) VALUES (206, 'Gietz', 8300.00, 9960.00);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Abel', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Ande', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Atkinson', 8);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Austin', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Baer', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Baida', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Banda', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Bates', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Bell', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Bernstein', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Bissot', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Bloom', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Bull', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Cabrio', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Cambrault', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Cambrault', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Chen', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Chung', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Colmenares', 10);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Davies', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('De Haan', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Dellinger', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Dilly', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Doran', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Ernst', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Errazuriz', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Everett', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Faviet', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Fay', 3);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Feeney', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Fleaur', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Fox', 3);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Fripp', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Gates', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Gee', 3);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Geoni', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Gietz', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Grant', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Grant', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Greenberg', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Greene', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Hall', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Hartstein', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Higgins', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Himuro', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Hunold', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Hutton', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Johnson', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Jones', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Kaufling', 8);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Khoo', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('King', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('King', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Kochhar', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Kumar', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Ladwig', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Landry', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Lee', 3);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Livingston', 10);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Lorentz', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Mallin', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Markle', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Marlow', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Marvins', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Matos', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Mavris', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('McCain', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('McEwen', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Mikkilineni', 11);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Mourgos', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Nayer', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('OConnell', 8);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Olsen', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Olson', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Ozer', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Partners', 8);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Pataballa', 9);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Patel', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Perkins', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Philtanker', 10);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Popp', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Rajs', 4);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Raphaely', 8);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Rogers', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Russell', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Sarchand', 8);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Sciarra', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Seo', 3);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Sewall', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Smith', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Smith', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Stiles', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Sullivan', 8);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Sully', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Taylor', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Taylor', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Tobias', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Tucker', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Tuvault', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Urman', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Vargas', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Vishney', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Vollman', 7);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Walsh', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Weiss', 5);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Whalen', 6);
INSERT INTO `单行函数练习` (`last_name`, `LENGTH(last_name)`) VALUES ('Zlotkey', 7);
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('100,King,24000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('101,Kochhar,17000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('102,De Haan,17000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('103,Hunold,9000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('104,Ernst,6000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('105,Austin,4800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('106,Pataballa,4800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('107,Lorentz,4200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('108,Greenberg,12000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('109,Faviet,9000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('110,Chen,8200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('111,Sciarra,7700.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('112,Urman,7800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('113,Popp,6900.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('114,Raphaely,11000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('115,Khoo,3100.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('116,Baida,2900.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('117,Tobias,2800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('118,Himuro,2600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('119,Colmenares,2500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('120,Weiss,8000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('121,Fripp,8200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('122,Kaufling,7900.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('123,Vollman,6500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('124,Mourgos,5800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('125,Nayer,3200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('126,Mikkilineni,2700.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('127,Landry,2400.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('128,Markle,2200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('129,Bissot,3300.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('130,Atkinson,2800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('131,Marlow,2500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('132,Olson,2100.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('133,Mallin,3300.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('134,Rogers,2900.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('135,Gee,2400.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('136,Philtanker,2200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('137,Ladwig,3600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('138,Stiles,3200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('139,Seo,2700.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('140,Patel,2500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('141,Rajs,3500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('142,Davies,3100.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('143,Matos,2600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('144,Vargas,2500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('145,Russell,14000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('146,Partners,13500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('147,Errazuriz,12000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('148,Cambrault,11000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('149,Zlotkey,10500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('150,Tucker,10000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('151,Bernstein,9500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('152,Hall,9000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('153,Olsen,8000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('154,Cambrault,7500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('155,Tuvault,7000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('156,King,10000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('157,Sully,9500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('158,McEwen,9000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('159,Smith,8000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('160,Doran,7500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('161,Sewall,7000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('162,Vishney,10500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('163,Greene,9500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('164,Marvins,7200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('165,Lee,6800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('166,Ande,6400.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('167,Banda,6200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('168,Ozer,11500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('169,Bloom,10000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('170,Fox,9600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('171,Smith,7400.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('172,Bates,7300.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('173,Kumar,6100.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('174,Abel,11000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('175,Hutton,8800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('176,Taylor,8600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('177,Livingston,8400.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('178,Grant,7000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('179,Johnson,6200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('180,Taylor,3200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('181,Fleaur,3100.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('182,Sullivan,2500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('183,Geoni,2800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('184,Sarchand,4200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('185,Bull,4100.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('186,Dellinger,3400.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('187,Cabrio,3000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('188,Chung,3800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('189,Dilly,3600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('190,Gates,2900.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('191,Perkins,2500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('192,Bell,4000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('193,Everett,3900.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('194,McCain,3200.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('195,Jones,2800.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('196,Walsh,3100.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('197,Feeney,3000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('198,OConnell,2600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('199,Grant,2600.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('200,Whalen,4400.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('201,Hartstein,13000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('202,Fay,6000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('203,Mavris,6500.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('204,Baer,10000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('205,Higgins,12000.00');
INSERT INTO `单行函数练习` (`OUT_PUT`) VALUES ('206,Gietz,8300.00');
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (36.2192, 13220);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (35.9671, 13128);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (33.9534, 12393);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (33.6685, 12289);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (32.2904, 11786);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (30.6384, 11183);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (29.2411, 10673);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (29.2411, 10673);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (29.2411, 10673);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (29.2411, 10673);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (29.0493, 10603);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (29.0466, 10602);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (28.7397, 10490);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (28.3425, 10345);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (28.2959, 10328);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (28.1397, 10271);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.8795, 10176);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.6000, 10074);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.5918, 10071);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.5781, 10066);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.5425, 10053);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.4986, 10037);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.3123, 9969);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.2192, 9935);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.1260, 9901);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (27.0877, 9887);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.9205, 9826);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.6575, 9730);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.5918, 9706);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.5890, 9705);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.5425, 9688);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.5315, 9684);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.5014, 9673);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.4822, 9666);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.4822, 9666);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.4795, 9665);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.4575, 9657);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.4438, 9652);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.3973, 9635);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.2192, 9570);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.1890, 9559);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.1315, 9538);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.1096, 9530);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.0548, 9510);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.0438, 9506);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.0356, 9503);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (26.0356, 9503);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.9288, 9464);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.9233, 9462);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.8959, 9452);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.8521, 9436);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.8411, 9432);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.8082, 9420);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.7151, 9386);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.6904, 9377);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.6055, 9346);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.6055, 9346);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.5726, 9334);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.5534, 9327);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.5233, 9316);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.4904, 9304);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.4685, 9296);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.4466, 9288);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.4438, 9287);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.4274, 9281);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.4082, 9274);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.3616, 9257);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.3589, 9256);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.2795, 9227);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.1918, 9195);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.1726, 9188);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.1507, 9180);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.1452, 9178);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (25.0192, 9132);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.9288, 9099);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.8301, 9063);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.7973, 9051);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.7315, 9027);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.6329, 8991);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.5671, 8967);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.5671, 8967);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.5233, 8951);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.4630, 8929);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.4575, 8927);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.4438, 8922);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.3973, 8905);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.2767, 8861);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.2000, 8833);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.2000, 8833);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (24.0630, 8783);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.8822, 8717);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.7945, 8685);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.7753, 8678);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.7370, 8664);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.7233, 8659);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.7041, 8652);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.6603, 8636);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.6356, 8627);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.6055, 8616);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.5918, 8611);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.5781, 8606);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.5699, 8603);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.5233, 8586);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.4849, 8572);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.4411, 8556);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.3644, 8528);
INSERT INTO `单行函数练习` (`worked_years`, `worked_days`) VALUES (23.3644, 8528);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Partners', '1997-01-05', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Errazuriz', '1997-03-10', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Cambrault', '1999-10-15', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Zlotkey', '2000-01-29', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Tucker', '1997-01-30', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Bernstein', '1997-03-24', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Hall', '1997-08-20', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Olsen', '1998-03-30', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Cambrault', '1998-12-09', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Tuvault', '1999-11-23', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Smith', '1997-03-10', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Doran', '1997-12-15', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Sewall', '1998-11-03', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Vishney', '1997-11-11', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Greene', '1999-03-19', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Marvins', '2000-01-24', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Lee', '2000-02-23', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Ande', '2000-03-24', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Banda', '2000-04-21', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Ozer', '1997-03-11', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Bloom', '1998-03-23', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Fox', '1998-01-24', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Smith', '1999-02-23', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Bates', '1999-03-24', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Kumar', '2000-04-21', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Hutton', '1997-03-19', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Taylor', '1998-03-24', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Livingston', '1998-04-23', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`, `department_id`) VALUES ('Johnson', '2000-01-04', 80);
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('King', '1987-06-17');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Kochhar', '1989-09-21');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('De Haan', '1993-01-13');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Hunold', '1990-01-03');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Ernst', '1991-05-21');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Greenberg', '1994-08-17');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Faviet', '1994-08-16');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Raphaely', '1994-12-07');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Khoo', '1995-05-18');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Kaufling', '1995-05-01');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Ladwig', '1995-07-14');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Rajs', '1995-10-17');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('King', '1996-01-30');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Sully', '1996-03-04');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Sarchand', '1996-01-27');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Bell', '1996-02-04');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Whalen', '1987-09-17');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Hartstein', '1996-02-17');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Mavris', '1994-06-07');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Baer', '1994-06-07');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Higgins', '1994-06-07');
INSERT INTO `单行函数练习` (`last_name`, `hire_date`) VALUES ('Gietz', '1994-06-07');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('King earns 24000 monthly but wants 72000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Kochhar earns 17000 monthly but wants 51000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('De Haan earns 17000 monthly but wants 51000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Hunold earns 9000 monthly but wants 27000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Ernst earns 6000 monthly but wants 18000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Austin earns 4800 monthly but wants 14400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Pataballa earns 4800 monthly but wants 14400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Lorentz earns 4200 monthly but wants 12600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Greenberg earns 12000 monthly but wants 36000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Faviet earns 9000 monthly but wants 27000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Chen earns 8200 monthly but wants 24600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Sciarra earns 7700 monthly but wants 23100');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Urman earns 7800 monthly but wants 23400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Popp earns 6900 monthly but wants 20700');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Raphaely earns 11000 monthly but wants 33000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Khoo earns 3100 monthly but wants 9300');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Baida earns 2900 monthly but wants 8700');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Tobias earns 2800 monthly but wants 8400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Himuro earns 2600 monthly but wants 7800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Colmenares earns 2500 monthly but wants 7500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Weiss earns 8000 monthly but wants 24000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Fripp earns 8200 monthly but wants 24600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Kaufling earns 7900 monthly but wants 23700');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Vollman earns 6500 monthly but wants 19500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Mourgos earns 5800 monthly but wants 17400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Nayer earns 3200 monthly but wants 9600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Mikkilineni earns 2700 monthly but wants 8100');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Landry earns 2400 monthly but wants 7200');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Markle earns 2200 monthly but wants 6600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Bissot earns 3300 monthly but wants 9900');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Atkinson earns 2800 monthly but wants 8400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Marlow earns 2500 monthly but wants 7500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Olson earns 2100 monthly but wants 6300');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Mallin earns 3300 monthly but wants 9900');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Rogers earns 2900 monthly but wants 8700');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Gee earns 2400 monthly but wants 7200');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Philtanker earns 2200 monthly but wants 6600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Ladwig earns 3600 monthly but wants 10800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Stiles earns 3200 monthly but wants 9600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Seo earns 2700 monthly but wants 8100');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Patel earns 2500 monthly but wants 7500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Rajs earns 3500 monthly but wants 10500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Davies earns 3100 monthly but wants 9300');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Matos earns 2600 monthly but wants 7800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Vargas earns 2500 monthly but wants 7500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Russell earns 14000 monthly but wants 42000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Partners earns 13500 monthly but wants 40500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Errazuriz earns 12000 monthly but wants 36000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Cambrault earns 11000 monthly but wants 33000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Zlotkey earns 10500 monthly but wants 31500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Tucker earns 10000 monthly but wants 30000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Bernstein earns 9500 monthly but wants 28500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Hall earns 9000 monthly but wants 27000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Olsen earns 8000 monthly but wants 24000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Cambrault earns 7500 monthly but wants 22500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Tuvault earns 7000 monthly but wants 21000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('King earns 10000 monthly but wants 30000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Sully earns 9500 monthly but wants 28500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('McEwen earns 9000 monthly but wants 27000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Smith earns 8000 monthly but wants 24000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Doran earns 7500 monthly but wants 22500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Sewall earns 7000 monthly but wants 21000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Vishney earns 10500 monthly but wants 31500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Greene earns 9500 monthly but wants 28500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Marvins earns 7200 monthly but wants 21600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Lee earns 6800 monthly but wants 20400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Ande earns 6400 monthly but wants 19200');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Banda earns 6200 monthly but wants 18600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Ozer earns 11500 monthly but wants 34500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Bloom earns 10000 monthly but wants 30000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Fox earns 9600 monthly but wants 28800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Smith earns 7400 monthly but wants 22200');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Bates earns 7300 monthly but wants 21900');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Kumar earns 6100 monthly but wants 18300');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Abel earns 11000 monthly but wants 33000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Hutton earns 8800 monthly but wants 26400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Taylor earns 8600 monthly but wants 25800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Livingston earns 8400 monthly but wants 25200');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Grant earns 7000 monthly but wants 21000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Johnson earns 6200 monthly but wants 18600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Taylor earns 3200 monthly but wants 9600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Fleaur earns 3100 monthly but wants 9300');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Sullivan earns 2500 monthly but wants 7500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Geoni earns 2800 monthly but wants 8400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Sarchand earns 4200 monthly but wants 12600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Bull earns 4100 monthly but wants 12300');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Dellinger earns 3400 monthly but wants 10200');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Cabrio earns 3000 monthly but wants 9000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Chung earns 3800 monthly but wants 11400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Dilly earns 3600 monthly but wants 10800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Gates earns 2900 monthly but wants 8700');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Perkins earns 2500 monthly but wants 7500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Bell earns 4000 monthly but wants 12000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Everett earns 3900 monthly but wants 11700');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('McCain earns 3200 monthly but wants 9600');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Jones earns 2800 monthly but wants 8400');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Walsh earns 3100 monthly but wants 9300');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Feeney earns 3000 monthly but wants 9000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('OConnell earns 2600 monthly but wants 7800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Grant earns 2600 monthly but wants 7800');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Whalen earns 4400 monthly but wants 13200');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Hartstein earns 13000 monthly but wants 39000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Fay earns 6000 monthly but wants 18000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Mavris earns 6500 monthly but wants 19500');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Baer earns 10000 monthly but wants 30000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Higgins earns 12000 monthly but wants 36000');
INSERT INTO `单行函数练习` (`Dream Salary`) VALUES ('Gietz earns 8300 monthly but wants 24900');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('King', 'AD_PRES', 'A');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Kochhar', 'AD_VP', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('De Haan', 'AD_VP', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Hunold', 'IT_PROG', 'C');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Ernst', 'IT_PROG', 'C');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Austin', 'IT_PROG', 'C');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Pataballa', 'IT_PROG', 'C');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Lorentz', 'IT_PROG', 'C');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Greenberg', 'FI_MGR', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Faviet', 'FI_ACCOUNT', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Chen', 'FI_ACCOUNT', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Sciarra', 'FI_ACCOUNT', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Urman', 'FI_ACCOUNT', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Popp', 'FI_ACCOUNT', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Raphaely', 'PU_MAN', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Khoo', 'PU_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Baida', 'PU_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Tobias', 'PU_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Himuro', 'PU_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Colmenares', 'PU_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Weiss', 'ST_MAN', 'B');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Fripp', 'ST_MAN', 'B');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Kaufling', 'ST_MAN', 'B');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Vollman', 'ST_MAN', 'B');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Mourgos', 'ST_MAN', 'B');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Nayer', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Mikkilineni', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Landry', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Markle', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Bissot', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Atkinson', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Marlow', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Olson', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Mallin', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Rogers', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Gee', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Philtanker', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Ladwig', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Stiles', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Seo', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Patel', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Rajs', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Davies', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Matos', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Vargas', 'ST_CLERK', 'E');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Russell', 'SA_MAN', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Partners', 'SA_MAN', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Errazuriz', 'SA_MAN', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Cambrault', 'SA_MAN', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Zlotkey', 'SA_MAN', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Tucker', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Bernstein', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Hall', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Olsen', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Cambrault', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Tuvault', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('King', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Sully', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('McEwen', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Smith', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Doran', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Sewall', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Vishney', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Greene', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Marvins', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Lee', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Ande', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Banda', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Ozer', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Bloom', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Fox', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Smith', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Bates', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Kumar', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Abel', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Hutton', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Taylor', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Livingston', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Grant', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Johnson', 'SA_REP', 'D');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Taylor', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Fleaur', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Sullivan', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Geoni', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Sarchand', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Bull', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Dellinger', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Cabrio', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Chung', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Dilly', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Gates', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Perkins', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Bell', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Everett', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('McCain', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Jones', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Walsh', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Feeney', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('OConnell', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Grant', 'SH_CLERK', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Whalen', 'AD_ASST', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Hartstein', 'MK_MAN', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Fay', 'MK_REP', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Mavris', 'HR_REP', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Baer', 'PR_REP', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Higgins', 'AC_MGR', 'F');
INSERT INTO `单行函数练习` (`last_name`, `job_id`, `grade`) VALUES ('Gietz', 'AC_ACCOUNT', 'F');
