INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('King', 90, 'Executive');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Kochhar', 90, 'Executive');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('De Haan', 90, 'Executive');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Hunold', 60, 'IT');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Ernst', 60, 'IT');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Austin', 60, 'IT');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Pataballa', 60, 'IT');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Lorentz', 60, 'IT');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Greenberg', 100, 'Finance');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Faviet', 100, 'Finance');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Chen', 100, 'Finance');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Sciarra', 100, 'Finance');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Urman', 100, 'Finance');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Popp', 100, 'Finance');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Raphaely', 30, 'Purchasing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Khoo', 30, 'Purchasing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Baida', 30, 'Purchasing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Tobias', 30, 'Purchasing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Himuro', 30, 'Purchasing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Colmenares', 30, 'Purchasing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Weiss', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Fripp', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Kaufling', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Vollman', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Mourgos', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Nayer', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Mikkilineni', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Landry', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Markle', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Bissot', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Atkinson', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Marlow', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Olson', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Mallin', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Rogers', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Gee', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Philtanker', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Ladwig', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Stiles', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Seo', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Patel', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Rajs', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Davies', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Matos', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Vargas', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Russell', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Partners', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Errazuriz', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Cambrault', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Zlotkey', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Tucker', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Bernstein', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Hall', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Olsen', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Cambrault', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Tuvault', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('King', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Sully', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('McEwen', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Smith', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Doran', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Sewall', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Vishney', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Greene', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Marvins', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Lee', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Ande', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Banda', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Ozer', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Bloom', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Fox', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Smith', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Bates', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Kumar', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Abel', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Hutton', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Taylor', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Livingston', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Grant', NULL, NULL);
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Johnson', 80, 'Sales');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Taylor', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Fleaur', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Sullivan', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Geoni', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Sarchand', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Bull', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Dellinger', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Cabrio', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Chung', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Dilly', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Gates', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Perkins', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Bell', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Everett', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('McCain', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Jones', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Walsh', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Feeney', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('OConnell', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Grant', 50, 'Shipping');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Whalen', 10, 'Administration');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Hartstein', 20, 'Marketing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Fay', 20, 'Marketing');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Mavris', 40, 'Human Resources');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Baer', 70, 'Public Relations');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Higgins', 110, 'Accounting');
INSERT INTO `多表查询练习` (`last_name`, `department_id`, `department_name`) VALUES ('Gietz', 110, 'Accounting');
INSERT INTO `多表查询练习` (`job_id`, `location_id`) VALUES ('AD_PRES', 1700);
INSERT INTO `多表查询练习` (`job_id`, `location_id`) VALUES ('AD_VP', 1700);
INSERT INTO `多表查询练习` (`job_id`, `location_id`) VALUES ('AD_VP', 1700);
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Russell', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Partners', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Errazuriz', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Cambrault', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Zlotkey', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Tucker', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Bernstein', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Hall', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Olsen', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Cambrault', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Tuvault', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('King', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Sully', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('McEwen', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Smith', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Doran', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Sewall', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Vishney', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Greene', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Marvins', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Lee', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Ande', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Banda', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Ozer', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Bloom', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Fox', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Smith', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Bates', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Kumar', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Abel', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Hutton', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Taylor', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Livingston', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Grant', NULL, NULL, NULL);
INSERT INTO `多表查询练习` (`last_name`, `department_name`, `location_id`, `city`) VALUES ('Johnson', 'Sales', 2500, 'Oxford');
INSERT INTO `多表查询练习` (`last_name`, `job_id`, `department_id`, `department_name`) VALUES ('Hartstein', 'MK_MAN', 20, 'Marketing');
INSERT INTO `多表查询练习` (`last_name`, `job_id`, `department_id`, `department_name`) VALUES ('Fay', 'MK_REP', 20, 'Marketing');
INSERT INTO `多表查询练习` (`department_name`, `street_address`, `last_name`, `job_id`, `salary`) VALUES ('Executive', '2004 Charade Rd', 'King', 'AD_PRES', 24000.00);
INSERT INTO `多表查询练习` (`department_name`, `street_address`, `last_name`, `job_id`, `salary`) VALUES ('Executive', '2004 Charade Rd', 'Kochhar', 'AD_VP', 17000.00);
INSERT INTO `多表查询练习` (`department_name`, `street_address`, `last_name`, `job_id`, `salary`) VALUES ('Executive', '2004 Charade Rd', 'De Haan', 'AD_VP', 17000.00);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('King', 100, 'King', 100);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Kochhar', 101, 'Kochhar', 101);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('De Haan', 102, 'De Haan', 102);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Hunold', 103, 'Hunold', 103);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Ernst', 104, 'Ernst', 104);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Austin', 105, 'Austin', 105);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Pataballa', 106, 'Pataballa', 106);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Lorentz', 107, 'Lorentz', 107);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Greenberg', 108, 'Greenberg', 108);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Faviet', 109, 'Faviet', 109);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Chen', 110, 'Chen', 110);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Sciarra', 111, 'Sciarra', 111);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Urman', 112, 'Urman', 112);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Popp', 113, 'Popp', 113);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Raphaely', 114, 'Raphaely', 114);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Khoo', 115, 'Khoo', 115);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Baida', 116, 'Baida', 116);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Tobias', 117, 'Tobias', 117);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Himuro', 118, 'Himuro', 118);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Colmenares', 119, 'Colmenares', 119);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Weiss', 120, 'Weiss', 120);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Fripp', 121, 'Fripp', 121);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Kaufling', 122, 'Kaufling', 122);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Vollman', 123, 'Vollman', 123);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Mourgos', 124, 'Mourgos', 124);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Nayer', 125, 'Nayer', 125);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Mikkilineni', 126, 'Mikkilineni', 126);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Landry', 127, 'Landry', 127);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Markle', 128, 'Markle', 128);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Bissot', 129, 'Bissot', 129);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Atkinson', 130, 'Atkinson', 130);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Marlow', 131, 'Marlow', 131);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Olson', 132, 'Olson', 132);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Mallin', 133, 'Mallin', 133);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Rogers', 134, 'Rogers', 134);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Gee', 135, 'Gee', 135);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Philtanker', 136, 'Philtanker', 136);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Ladwig', 137, 'Ladwig', 137);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Stiles', 138, 'Stiles', 138);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Seo', 139, 'Seo', 139);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Patel', 140, 'Patel', 140);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Rajs', 141, 'Rajs', 141);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Davies', 142, 'Davies', 142);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Matos', 143, 'Matos', 143);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Vargas', 144, 'Vargas', 144);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Russell', 145, 'Russell', 145);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Partners', 146, 'Partners', 146);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Errazuriz', 147, 'Errazuriz', 147);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Cambrault', 148, 'Cambrault', 148);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Zlotkey', 149, 'Zlotkey', 149);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Tucker', 150, 'Tucker', 150);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Bernstein', 151, 'Bernstein', 151);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Hall', 152, 'Hall', 152);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Olsen', 153, 'Olsen', 153);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Cambrault', 154, 'Cambrault', 154);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Tuvault', 155, 'Tuvault', 155);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('King', 156, 'King', 156);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Sully', 157, 'Sully', 157);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('McEwen', 158, 'McEwen', 158);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Smith', 159, 'Smith', 159);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Doran', 160, 'Doran', 160);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Sewall', 161, 'Sewall', 161);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Vishney', 162, 'Vishney', 162);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Greene', 163, 'Greene', 163);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Marvins', 164, 'Marvins', 164);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Lee', 165, 'Lee', 165);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Ande', 166, 'Ande', 166);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Banda', 167, 'Banda', 167);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Ozer', 168, 'Ozer', 168);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Bloom', 169, 'Bloom', 169);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Fox', 170, 'Fox', 170);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Smith', 171, 'Smith', 171);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Bates', 172, 'Bates', 172);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Kumar', 173, 'Kumar', 173);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Abel', 174, 'Abel', 174);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Hutton', 175, 'Hutton', 175);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Taylor', 176, 'Taylor', 176);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Livingston', 177, 'Livingston', 177);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Grant', 178, 'Grant', 178);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Johnson', 179, 'Johnson', 179);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Taylor', 180, 'Taylor', 180);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Fleaur', 181, 'Fleaur', 181);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Sullivan', 182, 'Sullivan', 182);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Geoni', 183, 'Geoni', 183);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Sarchand', 184, 'Sarchand', 184);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Bull', 185, 'Bull', 185);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Dellinger', 186, 'Dellinger', 186);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Cabrio', 187, 'Cabrio', 187);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Chung', 188, 'Chung', 188);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Dilly', 189, 'Dilly', 189);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Gates', 190, 'Gates', 190);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Perkins', 191, 'Perkins', 191);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Bell', 192, 'Bell', 192);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Everett', 193, 'Everett', 193);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('McCain', 194, 'McCain', 194);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Jones', 195, 'Jones', 195);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Walsh', 196, 'Walsh', 196);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Feeney', 197, 'Feeney', 197);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('OConnell', 198, 'OConnell', 198);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Grant', 199, 'Grant', 199);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Whalen', 200, 'Whalen', 200);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Hartstein', 201, 'Hartstein', 201);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Fay', 202, 'Fay', 202);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Mavris', 203, 'Mavris', 203);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Baer', 204, 'Baer', 204);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Higgins', 205, 'Higgins', 205);
INSERT INTO `多表查询练习` (`last_name`, `employee_id`, `last_name`, `employee_id`) VALUES ('Gietz', 206, 'Gietz', 206);
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Treasury');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Corporate Tax');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Control And Credit');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Shareholder Services');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Benefits');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Manufacturing');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Construction');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Contracting');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Operations');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('IT Support');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('NOC');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('IT Helpdesk');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Government Sales');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Retail Sales');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Recruiting');
INSERT INTO `多表查询练习` (`department_name`) VALUES ('Payroll');
INSERT INTO `多表查询练习` (`city`) VALUES ('Roma');
INSERT INTO `多表查询练习` (`city`) VALUES ('Venice');
INSERT INTO `多表查询练习` (`city`) VALUES ('Tokyo');
INSERT INTO `多表查询练习` (`city`) VALUES ('Hiroshima');
INSERT INTO `多表查询练习` (`city`) VALUES ('South Brunswick');
INSERT INTO `多表查询练习` (`city`) VALUES ('Whitehorse');
INSERT INTO `多表查询练习` (`city`) VALUES ('Beijing');
INSERT INTO `多表查询练习` (`city`) VALUES ('Bombay');
INSERT INTO `多表查询练习` (`city`) VALUES ('Sydney');
INSERT INTO `多表查询练习` (`city`) VALUES ('Singapore');
INSERT INTO `多表查询练习` (`city`) VALUES ('Stretford');
INSERT INTO `多表查询练习` (`city`) VALUES ('Sao Paulo');
INSERT INTO `多表查询练习` (`city`) VALUES ('Geneva');
INSERT INTO `多表查询练习` (`city`) VALUES ('Bern');
INSERT INTO `多表查询练习` (`city`) VALUES ('Utrecht');
INSERT INTO `多表查询练习` (`city`) VALUES ('Mexico City');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Hunold');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Ernst');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Austin');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Pataballa');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Lorentz');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Russell');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Partners');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Errazuriz');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Cambrault');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Zlotkey');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Tucker');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Bernstein');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Hall');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Olsen');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Cambrault');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Tuvault');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('King');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Sully');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('McEwen');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Smith');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Doran');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Sewall');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Vishney');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Greene');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Marvins');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Lee');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Ande');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Banda');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Ozer');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Bloom');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Fox');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Smith');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Bates');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Kumar');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Abel');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Hutton');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Taylor');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Livingston');
INSERT INTO `多表查询练习` (`last_name`) VALUES ('Johnson');
