INSERT INTO `算数运算符` (`100 + '1'`) VALUES (101);
INSERT INTO `算数运算符` (`100 + 'a'`) VALUES (100);
INSERT INTO `算数运算符` (`100 + 'NULL'`) VALUES (100);
INSERT INTO `算数运算符` (`12 % 3`, `12 % 5`) VALUES (0, 2);
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (100, 'King', 'Steven');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (102, 'De Haan', 'Lex');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (104, 'Ernst', 'Bruce');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (106, 'Pataballa', 'Valli');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (108, 'Greenberg', 'Nancy');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (110, 'Chen', 'John');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (112, 'Urman', 'Jose Manuel');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (114, 'Raphaely', 'Den');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (116, 'Baida', 'Shelli');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (118, 'Himuro', 'Guy');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (120, 'Weiss', 'Matthew');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (122, 'Kaufling', 'Payam');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (124, 'Mourgos', 'Kevin');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (126, 'Mikkilineni', 'Irene');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (128, 'Markle', 'Steven');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (130, 'Atkinson', 'Mozhe');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (132, 'Olson', 'TJ');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (134, 'Rogers', 'Michael');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (136, 'Philtanker', 'Hazel');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (138, 'Stiles', 'Stephen');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (140, 'Patel', 'Joshua');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (142, 'Davies', 'Curtis');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (144, 'Vargas', 'Peter');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (146, 'Partners', 'Karen');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (148, 'Cambrault', 'Gerald');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (150, 'Tucker', 'Peter');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (152, 'Hall', 'Peter');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (154, 'Cambrault', 'Nanette');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (156, 'King', 'Janette');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (158, 'McEwen', 'Allan');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (160, 'Doran', 'Louise');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (162, 'Vishney', 'Clara');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (164, 'Marvins', 'Mattea');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (166, 'Ande', 'Sundar');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (168, 'Ozer', 'Lisa');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (170, 'Fox', 'Tayler');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (172, 'Bates', 'Elizabeth');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (174, 'Abel', 'Ellen');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (176, 'Taylor', 'Jonathon');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (178, 'Grant', 'Kimberely');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (180, 'Taylor', 'Winston');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (182, 'Sullivan', 'Martha');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (184, 'Sarchand', 'Nandita');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (186, 'Dellinger', 'Julia');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (188, 'Chung', 'Kelly');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (190, 'Gates', 'Timothy');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (192, 'Bell', 'Sarah');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (194, 'McCain', 'Samuel');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (196, 'Walsh', 'Alana');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (198, 'OConnell', 'Donald');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (200, 'Whalen', 'Jennifer');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (202, 'Fay', 'Pat');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (204, 'Baer', 'Hermann');
INSERT INTO `算数运算符` (`employee_id`, `last_name`, `first_name`) VALUES (206, 'Gietz', 'William');
